### PR TITLE
Migrate instructions for disabling RO FW WP on Ti50 Chromebooks from chrultrabook docs

### PR DESCRIPTION
**Pull request by sadlerm4**
Instructions on disabling RO FW WP on Ti50 Chromebooks was recently added to the docs, I'm opening this PR as part of migrating this to your site instead (chrultrabook/docs#200). 

I've taken the liberty of adding it as a new page under firmware/wp where I think it makes sense, but please let me know how you would like best to integrate it with the rest of your site.

### CODE REVIEW

**Comment by MrChromebox** [comment]
there is already a small section on the RO firmware verification on disabling.md page, I don't think we need a separate page here just for this section, do you?

**Comment by sadlerm4** [comment]
I must be blind, I didn't see what you'd written for step 7 under disabling write protection. Yep totally get it now, you don't need this as well.

**Comment by MrChromebox** [comment]
I'm not saying we shouldn't expand on what I have, especially the bit on how to boot if RO verification is on, just that we should keep it all on the same page

**Comment by sadlerm4** [comment]
I'll work on doing that then. 

To use the CCD you need to run `gsctool -a -o` from ChromeOS on stock firmware the first time right? So if someone did end up bricking because they used a different method to disable hardware WP and didn't disable RO verification before flashing, even with the temporary fix, you would then need to reflash stock firmware, open the CCD and factory reset CCD flags with a SuzyQ?

Am I understanding that correctly?

**Comment by davidusrex** [comment]
Sorry for the late reply. So the temporary RO verification fix and that permanent fix you've explained aren't really related then. 

In that case, do you want me to attempt to include this

All you would need to do is:

- disconnect battery
- connect the SuzyQ to another device running Linux
- open the ttyUSB terminal
- ccd open
- ccd reset factory

as well?

**Comment by sadlerm4** [comment]
Sorry for the late reply. So the temporary RO verification fix isn't really related to the permanent fix that you've explained here. In that case, I think that your information is more useful than the current stated temporary workaround for booting when RO verification is still on, but I can find a way to include both methods in the docs.

**Comment by MrChromebox** [comment]
I went ahead and integrated these changes into the wp/disabling page, so don't think we need this PR anymore unless you think some changes are needed

**Pull request closed without merging**
