### PR TITLE
fixing list format

### PR DESCRIPTION
**Pull request by jkldgoefgkljefogeg**
This is a critical step necessary for both option 1 and 2

### CODE REVIEW

**Review by MrChromebox — APPROVED** [review]

**Comment by jkldgoefgkljefogeg** [comment]
How does the website gets updated? https://docs.chrultrabook.com/docs/unbricking/unbrick-suzyq.html hasn't picked this up

**Comment by MrChromebox** [comment]
> How does the website gets updated? https://docs.chrultrabook.com/docs/unbricking/unbrick-suzyq.html hasn't picked this up

same way as mine does: https://github.com/chrultrabook/docs/pull/

there is no automatic synchronization between the two sites

**Comment by jkldgoefgkljefogeg** [comment]
What is the history of these 2 sites where the contents are mostly identical?

**Comment by MrChromebox** [comment]
> What is the history of these 2 sites where the contents are mostly identical?

https://docs.mrchromebox.tech/docs/faq.html#how-are-the-mrchromebox-and-chrultrabook-projects-related

mrchromebox.tech was established back in 2017 or so, and focuses solely on firmware. The Chrultrabook project focuses on OS support. The chrultrabook website was set up a year or so ago to consolidate all the OS related info, and borrowed a lot of content from mrchromebox.tech (which they reorganized/reformatted). A few months ago, the mrchromebox.tech site was updated to a similar format as chrultrabook.com with updated content. chrultrabook.com is debating on whether to remove firmware-related content so as to not have an overlap (see their open PR for it)

**Pull request merged**
